project:
  type: posit-docs

website:
  title: "brand-docs-theme"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    #theme:
    #  - brand
    #css: styles.css
    toc: true



